site_name: netbox-zabbix
site_url: https://pergus.github.io/netbox-zabbix
repo_url: https://github.com/pergus/netbox-zabbix
repo_name: pergus/netbox-zabbix
#strict: true
nav:
  - Home: index.md
  - Installation & Setup:
    - Installation: installation.md
    - The Setup Zabbix Management Command: setup.md
  - User Guide: user_guide.md
  - Admin Guide: admin_guide.md
  - Programmer's Guide:
    - Core Concepts: programmer_guide.md
    - Scripting: script_provisioning.md
    - Models Reference:
      - Settings Model: settings_model.md
      - HostConfig Models: hostconfig_models.md
      - Template Model: template_model.md
      - Proxy Model: proxy_model.md
      - ProxyGroup Model: proxygroup_model.md
      - HostGroup Model: hostgroup_model.md
      - Mapping Models: mapping_models.md
      - DeviceMapping Model: devicemapping_model.md
      - VMMapping Model: vmmapping_model.md
      - TagMapping Model: tagmapping_model.md
      - InventoryMapping Model: inventorymapping_model.md
      - Maintenance Model: maintenance_model.md
      - BaseInterface Model: baseinterface_model.md
      - AgentInterface Model: agentinterface_model.md
      - SNMPInterface Model: snmpinterface_model.md
      - EventLog Model: eventlog_model.md
      - ZabbixAdminPermission Model: zabbixadminpermission_model.md
    - Jobs Reference:
      - Jobs Overview: jobs_overview.md
      - Job Classes Reference:
        - Validation Jobs:
          - ValidateHost Job: job_validatehost.md
        - Import Jobs:
          - ImportZabbixSettings Job: job_importzabbixsettings.md
          - ImportHost Job: job_importhost.md
        - Provisioning Jobs:
          - ProvisionAgent Job: job_provisionagent.md
          - ProvisionSNMP Job: job_provisionsnmp.md
        - Interface Jobs:
          - BaseZabbixInterfaceJob: job_basezabbixinterfacejob.md
          - CreateZabbixInterface Job: job_createzabbixinterface.md
          - UpdateZabbixInterface Job: job_updatezabbixinterface.md
        - Host Management Jobs:
          - CreateZabbixHost Job: job_createzabbixhost.md
          - UpdateZabbixHost Job: job_updatezabbixhost.md
          - DeleteZabbixHost Job: job_deletezabbixhost.md
        - System Jobs:
          - SyncHostsNow Job: job_synchostsnow.md
          - SystemJobImportZabbixSettings: job_systemjobimportzabbixsettings.md
          - SystemJobHostConfigSyncRefresh: job_systemjobhostconfigsyncrefresh.md
          - SystemJobMaintenanceCleanup: job_systemjobmaintenancecleanup.md
        - Base Classes:
          - AtomicJobRunner: job_atomicjobrunner.md
  - Contributing: contributing.md
  - Changelog: changelog.md
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  - meta
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pergus/netbox-zabbix
      name: Github
  # to enable disqus, uncomment the following and put your disqus id below
  # disqus: disqus_id
# uncomment the following and put your google tracking id below to enable GA
#google_analytics:
  #- UA-xxx
  #- auto